//===- Dialect.h - Dialect definition for the Toy IR ------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implements the IR Dialect for the Toy language.
// See docs/Tutorial/Toy/Ch-2.md for more information.
//
//===----------------------------------------------------------------------===//
#ifndef TOY_DIALECT_H
#define TOY_DIALECT_H

#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

namespace toy {

/// This is the definition of the Toy dialect. A dialect inherits from
/// mlir::Dialect and registers custom attributes, operations, and types. It can
/// also override virtual methods to change some general behavior, which will be
/// demonstrated in later chapters of the tutorial.
class Dialect : public mlir::Dialect {
  // These members are private!
  explicit Dialect(mlir::MLIRContext *ctx);

  /// Provide a utility accessor to the dialect namespace.
  //static llvm::StringRef getDialectNamespace() { return "toy"; } // in generated header,
  // this is a public member and has a return value of ::llvm::StringLiteral, see below.

  /// An initializer called from the constructor of toy::Dialect that is used
  /// to register attributes, operations, types, and more within the Toy
  /// dialect.
  void initialize();

  // From generated by TableGen Dialect.h.inc:
  friend class mlir::MLIRContext;

public:
  ~Dialect() override;
  static constexpr ::llvm::StringLiteral getDialectNamespace() {
    return ::llvm::StringLiteral("toy");
  }
};

} // namespace toy

// in the global namespace we have this in the generated code:
MLIR_DECLARE_EXPLICIT_TYPE_ID(::toy::Dialect)

#endif //TOY_DIALECT_H
